# Generated by Django 3.1.6 on 2021-02-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('PK', models.IntegerField(primary_key=True, serialize=False)),
                ('PKDif', models.IntegerField(blank=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Acronimo', models.CharField(blank=True, max_length=3)),
                ('CreditosGR', models.IntegerField()),
                ('CreditosGA', models.IntegerField()),
                ('IdAsignaturaAnterior', models.IntegerField(blank=True)),
                ('Curso', models.IntegerField()),
                ('Codigo', models.IntegerField()),
                ('Semestre', models.IntegerField()),
                ('TipoAsignatura', models.IntegerField(choices=[(1, 'Básica'), (2, 'Común'), (3, 'Obligatoria de Mención'), (4, 'Optativa'), (5, 'Trabajo de Fin de Grado'), (6, 'Prácticas de Empresa')])),
            ],
        ),
        migrations.CreateModel(
            name='AñoAsignatura',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Año', models.IntegerField()),
                ('Matriculados', models.IntegerField()),
                ('PK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('UmbralGA', models.FloatField()),
                ('UmbralGR', models.FloatField()),
                ('AsignaturaTitulo', models.ManyToManyField(to='app.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Letra', models.CharField(max_length=1)),
                ('Nuevos', models.IntegerField()),
                ('Repetidores', models.IntegerField()),
                ('Retenidos', models.IntegerField()),
                ('Plazas', models.IntegerField()),
                ('LibreConfiguracion', models.IntegerField()),
                ('OtrosTitulos', models.IntegerField()),
                ('Asimilado', models.IntegerField(blank=True)),
                ('Compartido', models.IntegerField(blank=True)),
                ('Turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1)),
                ('GruposReducidos', models.IntegerField()),
                ('IDAñoAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.añoasignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='IDMencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mencion'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Departamento', models.CharField(max_length=100)),
                ('Acronimo', models.CharField(blank=True, max_length=3)),
                ('AsignaturaArea', models.ManyToManyField(to='app.Asignatura')),
            ],
        ),
    ]
