# Generated by Django 3.1.6 on 2021-04-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='Codigo',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='PK',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mencion',
            name='Codigo',
            field=models.CharField(max_length=2),
        ),
    ]
